challenge:
  n_ch_per_epoch: 10
  docker_ulimit: 32768
  allowed_pip_pkg_dt: "2025-01-01T00:00:00Z"
  allowed_file_exts: [".py", ".json", ".yaml", ".yml", ".txt", ".pt"]
  bot_timeout: 30
  window_width: 1420
  window_height: 740
  n_checkboxes: 5
  cb_min_distance: 300
  cb_gen_max_factor: 20
  cb_size: 50
  cb_exclude_areas: [{ "x1": 500, "y1": 400, "x2": 950, "y2": 700 }]
  cb_pre_action_list:
    [
      [
        {
          "id": 0,
          "type": "click",
          "args": { "location": { "x": 510, "y": 58 } },
        },
        {
          "id": 1,
          "type": "click",
          "args": { "location": { "x": 1079, "y": 92 } },
        },
        {
          "id": 2,
          "type": "click",
          "args": { "location": { "x": 288, "y": 449 } },
        },
        {
          "id": 3,
          "type": "click",
          "args": { "location": { "x": 909, "y": 350 } },
        },
        {
          "id": 4,
          "type": "click",
          "args": { "location": { "x": 1314, "y": 289 } },
        },
      ],
      [
        {
          "id": 0,
          "type": "click",
          "args": { "location": { "x": 392, "y": 579 } },
        },
        {
          "id": 1,
          "type": "click",
          "args": { "location": { "x": 149, "y": 100 } },
        },
        {
          "id": 2,
          "type": "click",
          "args": { "location": { "x": 1359, "y": 485 } },
        },
        {
          "id": 3,
          "type": "click",
          "args": { "location": { "x": 1003, "y": 521 } },
        },
        {
          "id": 4,
          "type": "click",
          "args": { "location": { "x": 584, "y": 138 } },
        },
      ],
      [
        {
          "id": 0,
          "type": "click",
          "args": { "location": { "x": 141, "y": 396 } },
        },
        {
          "id": 1,
          "type": "click",
          "args": { "location": { "x": 1099, "y": 247 } },
        },
        {
          "id": 2,
          "type": "click",
          "args": { "location": { "x": 490, "y": 194 } },
        },
        {
          "id": 3,
          "type": "click",
          "args": { "location": { "x": 806, "y": 94 } },
        },
      ],
      [
        {
          "id": 0,
          "type": "click",
          "args": { "location": { "x": 719, "y": 164 } },
        },
        {
          "id": 1,
          "type": "click",
          "args": { "location": { "x": 285, "y": 484 } },
        },
        {
          "id": 2,
          "type": "click",
          "args": { "location": { "x": 1160, "y": 515 } },
        },
        {
          "id": 3,
          "type": "click",
          "args": { "location": { "x": 246, "y": 150 } },
        },
      ],
      [
        {
          "id": 0,
          "type": "click",
          "args": { "location": { "x": 328, "y": 567 } },
        },
        {
          "id": 1,
          "type": "click",
          "args": { "location": { "x": 1330, "y": 543 } },
        },
        {
          "id": 2,
          "type": "click",
          "args": { "location": { "x": 971, "y": 394 } },
        },
      ],
      [
        {
          "id": 0,
          "type": "click",
          "args": { "location": { "x": 556, "y": 296 } },
        },
        {
          "id": 1,
          "type": "click",
          "args": { "location": { "x": 330, "y": 70 } },
        },
        {
          "id": 2,
          "type": "click",
          "args": { "location": { "x": 960, "y": 96 } },
        },
      ],
      [
        {
          "id": 0,
          "type": "click",
          "args": { "location": { "x": 712, "y": 381 } },
        },
        {
          "id": 1,
          "type": "click",
          "args": { "location": { "x": 426, "y": 153 } },
        },
      ],
      [
        {
          "id": 0,
          "type": "click",
          "args": { "location": { "x": 186, "y": 564 } },
        },
      ],
    ]
